### ISSUE TITLE
分享图片没出现有图片

### ISSUE THREAD

**Issue by lichao0625** [rxreader/weibo_kit#33]

**Comment by v7lin** [comment]
以及升级 SDK 了，由于手上木有相应项目测试，只能麻烦你作测试了，记得将测试结果反馈给我，谢谢！
```yaml
dependencies:
  weibo_kit:
    git:
      url: https://github.com/rxreader/weibo_kit.git
```
