### ISSUE TITLE
部分安卓机图片分享不能正常展示图片()

### ISSUE THREAD

**Issue by NXliujunjie** [rxreader/weibo_kit#34]
https://user-images.githubusercontent.com/33019865/119936767-43f7c400-bfbc-11eb-8421-59bdce83a3ce.mp4

**Comment by v7lin** [comment]
以及升级 SDK 了，由于手上木有相应项目测试，只能麻烦你作测试了，记得将测试结果反馈给我，谢谢！
```yaml
dependencies:
  weibo_kit:
    git:
      url: https://github.com/rxreader/weibo_kit.git
```
